parameters:
  - name: environment
    type: string

  - name: dependsOn
    type: string

  - name: condition
    type: string
    default: succeeded()

stages:
  - stage: ${{ parameters.environment }}
    displayName: Release (${{ parameters.environment }})
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    jobs:
      - deployment: iac
        displayName: Deploy infrastructure
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: ${{ parameters.environment }}
                  inputs:
                    azureSubscription: ${{ parameters.environment }}
                    scriptType: pscore
                    scriptPath: iac/deploy.ps1
                    arguments: ${{ parameters.environment }}

      - deployment: app
        displayName: Deploy application
        environment: ${{ parameters.environment }}
        dependsOn: iac
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: ${{ parameters.environment }}
                  inputs:
                    azureSubscription: ${{ parameters.environment }}
                    appName: $(appName)
                    package: $(Agent.BuildDirectory)/**/*.zip
                    deploymentMethod: zipDeploy
