version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /**
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directories:
      - /pulumi/**
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directories:
      - /**
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directories:
      - /terraform/**
    schedule:
      interval: weekly
