name: Feature request
description: File a feature request
assignees:
  - mattiasholm
labels:
  - enhancement
title: "[Feature]: "

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please go through the following checklist before submitting
      options:
        # - label: I have verified that this feature has not yet been implemented in the latest commit on the main branch
        - label: I have verified that this feature has not been implemented in the latest commit on the main branch
          required: true
        - label: I have checked that this feature has not been requested already
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you're requesting
      placeholder: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    validations:
      required: true

  # - type: input
  #   id: commit
  #   attributes:
  #     label: Git commit ID
  #     description: Enter a Git commit ID where the problem exists
  #     placeholder: e6d5796360ad172a759bb478222ddd686c22848c
  #   validations:
  #     required: true

  # - type: dropdown
  #   id: platform
  #   attributes:
  #     label: Platform
  #     description: Select the platform you're using
  #     options:
  #       - Linux
  #       - macOS
  #       - Windows
  #   validations:
  #     required: true
