name: Bug report
description: File a bug report
labels:
  - bug
assignees:
  - mattiasholm

title: "[Bug]: "
body:
  # ??? [CHECKLIST] Have you checked that this bug has not been filed already??? VS true/false boolean?!
  # I'm using the latest commit on the main branch
  # I have checked that this bug has not been filed already
  # ???

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please go through the following checklist before submitting
      options:
        - label: I have checked that this bug has not been filed already
          required: true
        - label: I have verified that this has not been fixed in the latest commit on the main branch
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the problem you're experiencing
      placeholder: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    validations:
      required: true

  - type: input
    id: commit
    attributes:
      label: Git commit ID
      description: Enter the Git commit ID where the problem occurred
      placeholder: e6d5796360ad172a759bb478222ddd686c22848c
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email
      description: Enter your email address (optional)
      placeholder: example@domain.com
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
