name: Bug report
description: File a bug report
assignees:
  - mattiasholm
labels:
  - bug
title: "[Bug]: "

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please go through the following checklist before submitting
      options:
        - label: I have verified that this problem still exists in the latest commit on the main branch
          required: true
        - label: I have checked that this bug has not been reported already
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the problem you're experiencing
      placeholder: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    validations:
      required: true

  - type: input
    id: commit
    attributes:
      label: Git commit ID
      description: Enter a Git commit ID where the problem exists
      placeholder: e6d5796360ad172a759bb478222ddd686c22848c
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Select the platform you're using
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email
      description: Enter your email address (optional)
      placeholder: example@domain.com
    validations:
      required: false
