trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - .gitignore
      - README.md

pool:
  vmImage: ubuntu-latest

variables:
  workingDirectory: scripts

stages:
  - stage: test
    variables:
      - name: environment
        value: $(System.StageName)
      - group: test
    jobs:
      - deployment: Deploy
        environment: test
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - bash: ./deploy.sh $(environment) --pipeline
                  workingDirectory: $(workingDirectory)
                  env:
                    appId: $(appId)
                    password: $(password)
                    tenant: $(tenant)
  - stage: prod
    variables:
      - name: environment
        value: $(System.StageName)
      - group: prod
    jobs:
      - deployment: Deploy
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - bash: ./deploy.sh $(environment) --pipeline
                  workingDirectory: $(workingDirectory)
                  env:
                    appId: $(appId)
                    password: $(password)
                    tenant: $(tenant)
