trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - .gitignore
      - CHANGELOG.md
      - README.md
  batch: true

pool:
  vmImage: ubuntu-latest

stages:
  - stage: test
    variables:
      - group: test
    jobs:
      - job: Deploy
        steps:
          - bash: |
              ./deploy.sh $(System.StageName) --pipeline
            workingDirectory: scripts
            failOnStderr: false
            env:
              appId: $(appId)
              password: $(password)
  - stage: prod
    variables:
      - group: prod
    jobs:
      - job: Deploy
        steps:
          - bash: |
              ./deploy.sh $(System.StageName) --pipeline
            workingDirectory: scripts
            failOnStderr: false
            env:
              appId: $(appId)
              password: $(password)
