subscription='804fd219-0c15-45f9-ae36-0a4d3725848f'
resourceGroup='rg-holm-arm-01'
location='WestEurope'
tags=(
    'Application=ARM'
    'Company=Holm'
    'Environment=Development'
    'Owner=mattias.holm@b3cloud.onmicrosoft.com'
)
template='main.json'
parameters='parameters.json'
module='./arm-ttk/arm-ttk/arm-ttk.psd1'
