parameters:
  - name: environment
    type: string

  - name: dependsOn
    type: string

  - name: condition
    type: string

stages:
  - stage: ${{ parameters.environment }}
    displayName: Release (${{ parameters.environment }})
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    jobs:
      - deployment: iac
        displayName: Deploy Infrastructure
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: script.yml
                  parameters:
                    environment: ${{ parameters.environment }}

      - deployment: func
        displayName: Deploy Function App
        environment: ${{ parameters.environment }}
        dependsOn: iac
        condition: succeeded()
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  displayName: ${{ parameters.environment }}
                  inputs:
                    azureSubscription: ${{ parameters.environment }}
                    appName: $(appName)
                    package: $(Agent.BuildDirectory)/**/*.zip
                    deploymentMethod: zipDeploy
