parameters:
  - name: environment
    type: string

  - name: dependsOn
    type: string

  - name: condition
    type: string

stages:
  - stage: ${{ parameters.environment }}
    displayName: Release (${{ parameters.environment }})
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    jobs:
      - deployment: release
        displayName: Release
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  displayName: Deploy Function App
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appName: $(appName)
                    package: $(Agent.BuildDirectory)/**/*.zip
