trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ci
      - iac
      - src

pool:
  vmImage: ubuntu-latest

variables:
  appName: app-$(Environment.Name)-01

stages:
  - template: templates/build.yml
    parameters:
      environments:
        - tst
        - stg
        - prod

  - template: templates/release.yml
    parameters:
      environment: tst
      dependsOn: build

  - template: templates/release.yml
    parameters:
      environment: stg
      dependsOn: tst
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  - template: templates/release.yml
    parameters:
      environment: prod
      dependsOn: stg
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
