choco install -y vscode
choco install -y git
choco install -y python3
choco install -y powershell-core
choco install -y azure-cli
choco install -y kubernetes-cli
choco install -y azure-data-studio
choco install -y microsoftazurestorageexplorer
choco install -y docker-desktop
choco install -y googlechrome
choco install -y office365proplus
choco install -y onenote
choco install -y microsoft-teams
choco install -y teamviewer
choco install -y dropbox
choco install -y gimp
choco install -y vlc
choco install -y spotify
choco install -y nestopia
choco install -y wsl
choco install -y wsl-ubuntu-1804
choco install -y 7zip
choco install -y winscp
choco install -y vim
choco install -y greenshot
choco install -y sql-server-express
choco install -y filezilla
choco install -y jabra-direct
choco install -y microsoft-windows-terminal