name: Azure Pulumi

on:
  push:
    branches:
      - main
    paths:
      - pulumi/azure-python/**
      - .github/workflows/azure-pulumi.yml
      - "!**.md"

  workflow_dispatch:

  pull_request:

defaults:
  run:
    shell: bash
    working-directory: terraform/azure

env:
  stack: dev
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Pulumi Preview
        run: pulumi preview --stack $stack --refresh #--yes

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # - name: Setup cache
      #   uses: actions/cache@v2
      #   with:
      #     path: /home/runner/.cache/pip
      #     # path: |
      #     #   /home/runner/.pulumi
      #     #   /home/runner/.cache/pip
      #     # key: ${{ matrix.os }}-pulumi-${{ hashFiles('requirements.txt') }}
      #     # key: ${{ matrix.os }}-${{ hashFiles('requirements.txt') }}
      #     # key: ${{ hashFiles('requirements.txt') }} # Funkar ej???
      #     # key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      #     key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      #
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: pip install -r requirements.txt
      #

      - name: Pulumi Up
        run: pulumi up --stack $stack #--yes
