name: Azure All

on:
  workflow_dispatch:

jobs:
  public:
    uses: mattiasholm/code/.github/workflows/azure-arm.yml@main
  public2:
    uses: mattiasholm/code/.github/workflows/azure-arm.yml
  local:
    uses: ./.github/workflows/azure-arm.yml
