name: Azure Terraform

on:
  push:
    branches:
      - main
    paths:
      - "terraform/azure/**"
      - "!**.md"

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Authenticate to Terraform Cloud
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # - name: Authenticate to Azure
      #   run: |
      #     export ARM_CLIENT_ID="${appId}"
      #     export ARM_CLIENT_SECRET="${password}"
      #     export ARM_SUBSCRIPTION_ID="${subscriptionId}"
      #     export ARM_TENANT_ID="${tenant}"
      #   env:
      #     appId: ${{ secrets.appId }}
      #     password: ${{ secrets.password }}
      #     subscriptionId: ${{ secrets.subscriptionId }}
      #     tenant: ${{ secrets.tenant }}

      - name: terraform fmt
        run: terraform fmt --check
        working-directory: terraform/azure
        
      - name: terraform init
        run: terraform init --input=false
        working-directory: terraform/azure

      - name: terraform plan
        run: |
          # export ARM_CLIENT_ID="${appId}"
          # export ARM_CLIENT_SECRET="${password}"
          # export ARM_SUBSCRIPTION_ID="${subscriptionId}"
          # export ARM_TENANT_ID="${tenant}"

          terraform plan -out=tfplan -input=false
        working-directory: terraform/azure
        env:
          appId: ${{ secrets.appId }}
          password: ${{ secrets.password }}
          subscriptionId: ${{ secrets.subscriptionId }}
          tenant: ${{ secrets.tenant }}

      - name: terraform apply
        run: terraform apply -input=false tfplan
        working-directory: terraform/azure
