name: Azure TypeScript

on:
  push:
    branches:
      - main
    paths:
      - pulumi/azure-typescript/**
      - .github/workflows/azure-typescript.yml
      - "!**.md"

  workflow_dispatch:

  pull_request:

defaults:
  run:
    working-directory: pulumi/azure-typescript

env:
  path: pulumi/azure-typescript
  stack: dev
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --production

      # - name: Setup cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ env.path }}/node_modules/
      #     key: ${{ runner.os }}-${{ hashFiles(format('{0}/package.json', env.path)) }}

      - name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          command: preview
          work-dir: ${{ env.path }}
          stack-name: ${{ env.stack }}
          refresh: true

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --production

      # - name: Setup cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ env.path }}/node_modules/
      #     key: ${{ runner.os }}-${{ hashFiles(format('{0}/package.json', env.path)) }}

      - name: Pulumi Up
        uses: pulumi/actions@v3
        with:
          command: up
          work-dir: ${{ env.path }}
          stack-name: ${{ env.stack }}
