name: Azure Pulumi

on:
  push:
    branches:
      - main
    paths:
      - "pulumi/azure-python/**"
      - ".github/workflows/azure-pulumi.yml"
      - "!**.md"

  workflow_dispatch:

  pull_request:

env:
  work-dir: pulumi/azure-python

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          work-dir: pulumi/azure-python
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.appId }}
          ARM_CLIENT_SECRET: ${{ secrets.password }}
          ARM_TENANT_ID: ${{ secrets.tenant }}

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Pulumi Up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: pulumi/azure-python
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.appId }}
          ARM_CLIENT_SECRET: ${{ secrets.password }}
          ARM_TENANT_ID: ${{ secrets.tenant }}
