name: Azure Bicep

on:
  push:
    branches:
      - main
    paths:
      - azure/bicep/**
      - .github/workflows/azure-bicep.yml
      - "!**.md"

  workflow_dispatch:

  pull_request:

defaults:
  run:
    working-directory: azure/bicep

env:
  config: main.config
  # args: --subscription $subscriptionId --location $location --template-file $templateFile --parameters @$parameterFile

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Load configuration
        run: |
          . $config
          echo $subscriptionId
          echo $location
          echo $templateFile
          echo $parameterFile

      - name: Validate deployment
        run: az deployment sub validate --subscription $subscriptionId --location $location --template-file $templateFile --parameters @$parameterFile

      - name: What-if deployment
        run: az deployment sub what-if --subscription $subscriptionId --location $location --template-file $templateFile --parameters @$parameterFile

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Load configuration
        run: . $config

      - name: Create deployment
        run: az deployment sub create --subscription $subscriptionId --location $location --template-file $templateFile --parameters @$parameterFile
