name: Azure Pulumi

on:
  push:
    branches:
      - main
    paths:
      - pulumi/azure-python/**
      - .github/workflows/azure-pulumi.yml
      - "!**.md"

  pull_request:
    paths:
      - pulumi/azure-python/**
      - .github/workflows/azure-pulumi.yml
      - "!**.md"

  workflow_dispatch:

env:
  path: pulumi/azure-python
  stack: dev
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ${{ env.path }}/venv/
          key: ${{ runner.os }}-${{ hashFiles(format('{0}/requirements.txt', env.path)) }}

      - name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          command: preview
          work-dir: ${{ env.path }}
          stack-name: ${{ env.stack }}
          refresh: true

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://foo.holm.io/
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ${{ env.path }}/venv/
          key: ${{ runner.os }}-${{ hashFiles(format('{0}/requirements.txt', env.path)) }}

      - name: Pulumi Up
        uses: pulumi/actions@v3
        with:
          command: up
          work-dir: ${{ env.path }}
          stack-name: ${{ env.stack }}
