name: Azure ARM

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/azure-arm.yml
      - azure/arm/**
      - "!**.md"

  pull_request:
    paths:
      - .github/workflows/azure-arm.yml
      - azure/arm/**
      - "!**.md"

  workflow_dispatch:
    inputs:
      debug:
        description: Debug
        type: boolean

  workflow_call:

permissions:
  contents: read
  id-token: write

defaults:
  run:
    working-directory: azure/arm

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run linter
        run: ./lint.ps1

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Create resource group
        run: ./rg.sh

      - name: Validate deployment
        run: ./validate.sh

      - name: What-if deployment
        run: ./whatif.sh

      - name: Debug
        if: inputs.debug && (success() || failure())
        uses: mxschmitt/action-tmate@v3

  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://arm.holm.io/
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Create deployment
        run: ./deploy.sh

      - name: Debug
        if: inputs.debug && (success() || failure())
        uses: mxschmitt/action-tmate@v3
