name: Azure Terraform

on:
  push:
    branches:
      - main
    paths:
      - "terraform/azure/**"
      - ".github/workflows/azure-tf.yml"
      - "!**.md"

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    env:
      working-directory: terraform/azure
      ARM_CLIENT_ID: ${{ secrets.appId }}
      ARM_CLIENT_SECRET: ${{ secrets.password }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.subscriptionId }}
      ARM_TENANT_ID: ${{ secrets.tenant }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache plugin dir
        uses: actions/cache@v2
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --format compact

      - name: terraform init
        run: terraform init -input=false
        working-directory: ${{ env.working-directory }}

      - name: terraform plan
        run: terraform plan -out=tfplan -input=false
        working-directory: ${{ env.working-directory }}

      - name: terraform apply
        run: terraform apply -input=false tfplan
        working-directory: ${{ env.working-directory }}
