name: Azure Pulumi

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/azure-pulumi.yml
      - pulumi/azure-python/**
      - "!**.md"

  pull_request:
    paths:
      - .github/workflows/azure-pulumi.yml
      - pulumi/azure-python/**
      - "!**.md"

  workflow_dispatch:
    inputs:
      debug:
        description: Debug
        type: boolean

  workflow_call:

permissions:
  contents: read
  id-token: write

env:
  path: pulumi/azure-python
  stack: dev
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: 9b184a26-7fff-49ed-9230-d11d484ad51b # Tmp hardcoded
  ARM_USE_OIDC: true
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ${{ env.path }}/venv/
          key: ${{ runner.os }}-${{ hashFiles(format('{0}/requirements.txt', env.path)) }}

      - name: Pulumi - Preview
        uses: pulumi/actions@v4
        with:
          command: preview
          work-dir: ${{ env.path }}
          stack-name: ${{ env.stack }}

      - name: Debug
        if: inputs.debug && (success() || failure())
        uses: mxschmitt/action-tmate@v3

  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ${{ vars.RUNNER }}
    environment:
      name: dev
      url: https://pulumi.holm.io/
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ${{ env.path }}/venv/
          key: ${{ runner.os }}-${{ hashFiles(format('{0}/requirements.txt', env.path)) }}

      - name: Pulumi - Up
        uses: pulumi/actions@v4
        with:
          command: up
          work-dir: ${{ env.path }}
          stack-name: ${{ env.stack }}

      - name: Debug
        if: inputs.debug && (success() || failure())
        uses: mxschmitt/action-tmate@v3
