name: Azure ARM

on:
  push:
    branches:
      - main
    paths:
      - "azure/arm/**"
      - ".github/workflows/azure-arm.yml"
      - "!**.md"
  pull_request:

  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: azure/arm

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Validate infrastructure
        run: ./validate.sh

  release:
    name: Release
    # if: ${{ github.event_name == 'push' }}
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy infrastructure
        run: ./deploy.sh
        env:
          appId: ${{ secrets.appId }}
          password: ${{ secrets.password }}
          tenant: ${{ secrets.tenant }}
