name: Azure Bicep 2

on:
  push:
    branches:
      - main
    paths:
      - "azure/bicep/**"
      - ".github/workflows/azure-bicep2.yml"
      - "!**.md"

  workflow_dispatch:

  pull_request:

env:
  templateFile: azure/bicep/main.bicep
  location: WestEurope

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate infrastructure
        run: az deployment sub validate --template-file $templateFile --location $location
