name: Azure Python

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/azure-python.yml
      - pulumi/azure-python/**
      - "!**.md"
      - "!**.gitignore"

  pull_request:
    paths:
      - .github/workflows/azure-python.yml
      - pulumi/azure-python/**
      - "!**.md"
      - "!**.gitignore"

  workflow_dispatch:
    inputs:
      debug:
        description: Debug
        type: boolean

  workflow_call:

permissions:
  contents: read
  id-token: write

defaults: # TESTA!
  run:
    working-directory: pulumi/azure-python

env:
  path: pulumi/azure-python
  stack: dev
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_USE_OIDC: true
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache virtual environment
        uses: actions/cache@v4
        with:
          path: ${{ env.path }}/venv/
          key: ${{ runner.os }}-venv-${{ hashFiles(format('{0}/requirements.txt', env.path)) }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install dependencies # TESTA!
        run: python -m venv venv && venv/bin/pip install -r requirements.txt

      - name: Pulumi - Preview
        uses: pulumi/actions@v6
        with:
          pulumi-version: "~${{ vars.PULUMI_VERSION }}"
          command: preview
          work-dir: ${{ env.path }}
          stack-name: ${{ env.stack }}

      - name: Debug
        if: inputs.debug && (success() || failure())
        uses: mxschmitt/action-tmate@v3

  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ${{ vars.RUNNER }}
    environment:
      name: dev
      url: https://app.holm.io/
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache virtual environment
        uses: actions/cache@v4
        with:
          path: ${{ env.path }}/venv/
          key: ${{ runner.os }}-venv-${{ hashFiles(format('{0}/requirements.txt', env.path)) }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Pulumi - Up
        uses: pulumi/actions@v6
        with:
          pulumi-version: "~${{ vars.PULUMI_VERSION }}"
          command: up
          work-dir: ${{ env.path }}
          stack-name: ${{ env.stack }}

      - name: Debug
        if: inputs.debug && (success() || failure())
        uses: mxschmitt/action-tmate@v3
