name: Azure ARM

on:
  push:
    branches:
      - main
    paths:
      - "azure/arm/**"
      - "!**.md"

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    env:
      working-directory: azure/arm
      appId: ${{ secrets.appId }}
      password: ${{ secrets.password }}
      tenant: ${{ secrets.tenant }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run lint script
        run: ./lint.sh
        working-directory: ${{ env.working-directory }}

      - name: Run deploy script
        run: ./deploy.sh
        working-directory: ${{ env.working-directory }}
