name: Azure Terraform

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/azure-terraform.yml
      - terraform/azure/**
      - "!**.md"

  pull_request:
    paths:
      - .github/workflows/azure-terraform.yml
      - terraform/azure/**
      - "!**.md"

  workflow_dispatch:
    inputs:
      debug:
        description: Debug
        type: boolean

  workflow_call:

defaults:
  run:
    working-directory: terraform/azure

env:
  path: terraform/azure
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_USE_OIDC: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan -out=tfplan -input=false

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ${{ env.path }}/tfplan

      - name: Set up remote debugging
        if: inputs.debug && (success() || failure())
        uses: mxschmitt/action-tmate@v3

  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://terraform.holm.io/
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ${{ env.path }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Apply Terraform
        run: terraform apply -input=false tfplan

      - name: Set up remote debugging
        if: inputs.debug && (success() || failure())
        uses: mxschmitt/action-tmate@v3
