name: Azure Terraform

on:
  push:
    branches:
      - main
    paths:
      - terraform/azure/**
      - .github/workflows/azure-terraform.yml
      - "!**.md"

  workflow_dispatch:

  pull_request:

defaults:
  run:
    shell: bash
    working-directory: terraform/azure

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      #
      - name: Terraform Format
        run: terraform fmt -check

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # - name: Terraform Initialize
      #   run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color
      #

      # - name: Setup TFLint
      #   uses: terraform-linters/setup-tflint@v1

      # - name: Initialize TFLint
      #   run: tflint --init

      # - name: Run TFLint
      #   run: tflint --format json

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Plan Terraform
        run: terraform plan -out=tfplan -input=false

      - name: Apply Terraform
        run: terraform apply -input=false tfplan
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
