name: Azure Pulumi

on:
  push:
    branches:
      - main
    paths:
      - pulumi/azure-python/**
      - .github/workflows/azure-pulumi.yml
      - "!**.md"

  workflow_dispatch:

  pull_request:

env:
  stack-name: dev
  work-dir: pulumi/azure-python
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ${{ env.stack-name }}
          work-dir: ${{ env.work-dir }}
          refresh: true

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Test with cache
      - name: Cache Pulumi
        uses: actions/cache@v2
        with:
          # path: ~/.tflint.d/plugins
          path: /home/runner/.pulumi
          # key: ${{ matrix.os }}-pulumi-${{ hashFiles('requirements.txt') }}
          key: ${{ matrix.os }}-${{ hashFiles('requirements.txt') }}
      #

      - name: Pulumi Up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.stack-name }}
          work-dir: ${{ env.work-dir }}

      # Temporary test with consecutive deployment in the same job:
      - name: Pulumi Up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.stack-name }}
          work-dir: ${{ env.work-dir }}
      #
