name: Azure Terraform

on:
  push:
    branches:
      - main
    paths:
      - "terraform/azure/**"
      - "!**.md"

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Terraform Cloud
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Run deploy script
        run: ./deploy.sh
        shell: bash
        working-directory: terraform/azure
        env:
          appId: ${{ secrets.appId }}
          password: ${{ secrets.password }}
          tenant: ${{ secrets.tenant }}
