name: Azure Terraform

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/azure-terraform.yml
      - terraform/azure/**
      - "!**.md"

  pull_request:
    paths:
      - .github/workflows/azure-terraform.yml
      - terraform/azure/**
      - "!**.md"

  workflow_dispatch:

  workflow_call:

defaults:
  run:
    working-directory: terraform/azure

env:
  path: terraform/azure
  # ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  # ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} #

jobs:
  build:
    name: Build
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Initialize
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ${{ env.path }}/tfplan

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://terraform.holm.io/
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ${{ env.path }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Initialize
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false tfplan
