name: Azure Bicep

on:
  push:
    branches:
      - main
    paths:
      - "azure/bicep/**"
      - ".github/workflows/azure-bicep.yml"
      - "!**.md"

  workflow_dispatch:

  pull_request:

defaults:
  run:
    shell: bash
    working-directory: azure/bicep

env:
  appId: ${{ secrets.appId }}
  password: ${{ secrets.password }}
  tenant: ${{ secrets.tenant }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Validate infrastructure
        run: ./validate.sh

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy infrastructure
        run: ./deploy.sh
