name: Azure Bicep

on:
  push:
    branches:
      - main
    paths:
      - azure/bicep/**
      - .github/workflows/azure-bicep.yml
      - "!**.md"

  pull_request:

  workflow_dispatch:

defaults:
  run:
    working-directory: azure/bicep

env:
  config: main.config

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate deployment
        run: |
          . $config
          az deployment sub validate --subscription $subscription --location $location --template-file $template --parameters @$parameters

      - name: What-if deployment
        run: |
          . $config
          az deployment sub what-if --subscription $subscription --location $location --template-file $template --parameters @$parameters

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create deployment
        run: |
          . $config
          az deployment sub create --subscription $subscription --location $location --template-file $template --parameters @$parameters
