name: Azure Bicep

on:
  push:
    branches:
      - main
    paths:
      - azure/bicep/**
      - .github/workflows/azure-bicep.yml
      - "!**.md"

  workflow_dispatch:

  pull_request:

defaults:
  run:
    shell: bash
    working-directory: azure/bicep

env:
  location: WestEurope
  templateFile: main.bicep

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate deployment
        run: az deployment sub validate --location $location --template-file $templateFile

      - name: What-if deployment
        run: az deployment sub what-if --location $location --template-file $templateFile

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create deployment
        run: az deployment sub create --location $location --template-file $templateFile
