name: Azure ARM

on:
  push:
    branches:
      - main
    paths:
      - "azure/arm/**"
      - ".github/workflows/azure-arm.yml"
      - "!**.md"

  workflow_dispatch:

env:
  runs-on: ubuntu-latest

defaults:
  run:
    shell: bash
    working-directory: azure/arm

jobs:
  build:
    name: Build
    runs-on: ${{ env.runs-on }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Validate infrastructure
        run: ./validate.sh

  release:
    name: Release
    needs: build
    runs-on: ${{ env.runs-on }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Deploy infrastructure
        env:
          appId: ${{ secrets.appId }}
          password: ${{ secrets.password }}
          tenant: ${{ secrets.tenant }}
        run: ./deploy.sh
