name: Azure Pulumi

on:
  push:
    branches:
      - main
    paths:
      - pulumi/azure-python/**
      - .github/workflows/azure-pulumi.yml
      - "!**.md"

  workflow_dispatch:

  pull_request:

defaults:
  run:
    shell: bash
    working-directory: pulumi/azure-python

env:
  stack: dev
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v2

  #     - name: Pulumi Preview
  #       run: pulumi preview --refresh --stack $stack --yes

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          # path: ~/.cache/pip
          path: pulumi/azure-python/venv/
          # path: ${{ RUNNER_TOOL_CACHE }}/Python
          # path: |
          #   ~/.cache/pip
          #   ~/.pulumi
          #   /usr/bin/python3
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          # key: ${{ runner.os }}-pip-${{ hashFiles('pulumi/azure-python/requirements.txt') }}
          # key: ${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          # key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          # key: ${{ runner.os }}-pulumi-${{ hashFiles('**/requirements.txt') }}
          # restore-keys: ${{ runner.os }}-pip-
          # restore-keys: ${{ runner.os }}-test

      # - name: Setup cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ env.pythonLocation }}
      #     key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
      #     # key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt') }}
      #     # key: /usr/bin/python3-${{ hashFiles('setup.py') }}-${{ hashFiles('**/requirements.txt') }}
      #     # key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

      - name: Pulumi Up
        run: pulumi up --stack $stack --yes
