name: Azure ARM

on:
  push:
    branches:
      - main
    paths:
      - "azure/arm/**"
      - ".github/workflows/azure-arm.yml"
      - "!**.md"

  workflow_dispatch:

  pull_request:

defaults:
  run:
    shell: bash
    working-directory: azure/arm

env:
  templateFile: azure/arm/main.json
  location: WestEurope

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run arm-ttk
        run: ./arm-ttk.sh

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate deployment
        run: az deployment sub validate --template-file $templateFile --location $location

      - name: What-if deployment
        run: az deployment sub what-if --template-file $templateFile --location $location

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create deployment
        run: az deployment sub create --template-file $templateFile --location $location
