name: Azure Bicep

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/azure-bicep.yml # Test
      - azure/bicep/**
      - "!**.md"

  pull_request:
    paths:
      - .github/workflows/azure-bicep.yml
      - azure/bicep/**
      - "!**.md"

  workflow_dispatch:

  workflow_call:

permissions:
  id-token: write

defaults:
  run:
    working-directory: azure/bicep

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true

      - name: Validate deployment
        run: ./validate.sh

      - name: What-if deployment
        run: ./whatif.sh

  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://bicep.holm.io/
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true

      - name: Create deployment
        run: ./deploy.sh
