name: Azure Bicep

on:
  push:
    branches:
      - main
    paths:
      - "azure/bicep/**"
      - "!**.md"

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Bicep templates
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run deploy script
        run: |
          cd ./azure/bicep
          ./deploy.sh
        env:
          appId: ${{ secrets.appId }}
          password: ${{ secrets.password }}
