name: Azure Bicep

on:
  push:
    branches:
      - main
    paths:
    - 'azure/bicep'
    - '!**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run deploy script
        run: |
          cd ./azure/bicep
          ./temp.sh
