name: Debug

on:
  workflow_dispatch:
    inputs:
      debug:
        description: Debug
        type: boolean

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Start remote debugging
        if: inputs.debug && (success() || failure())
        uses: mxschmitt/action-tmate@v3
