name: Debug

on:
  workflow_dispatch:

env:
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Set up remote debugging
        uses: mxschmitt/action-tmate@v3
