name: Debug

on:
  workflow_dispatch:
    inputs:
      debug:
        description: Debug
        type: boolean

env:
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  secrets: ${{ secrets }}

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up tmate
        if: inputs.debug && (success() || failure())
        uses: mxschmitt/action-tmate@v3
