name: Run All

on:
  workflow_dispatch:

jobs:
  azure-arm:
    uses: ${{ env.path }}/azure-arm.yml
    secrets: inherit

  azure-bicep:
    uses: ${{ env.path }}/azure-bicep.yml
    secrets: inherit

  azure-pulumi:
    uses: ${{ env.path }}/azure-pulumi.yml
    secrets: inherit

  azure-terraform:
    uses: ${{ env.path }}/azure-terraform.yml
    secrets: inherit
