name: Run All

on:
  workflow_dispatch:

jobs:
  azure-arm:
    uses: ./.github/workflows/${{ github.job }}.yml
    secrets: inherit

  azure-bicep:
    uses: ./.github/workflows/${{ github.job }}.yml
    secrets: inherit

  azure-pulumi:
    uses: ./.github/workflows/${{ github.job }}.yml
    secrets: inherit

  azure-terraform:
    uses: ./.github/workflows/${{ github.job }}.yml
    secrets: inherit
