# name: tmate
name: Debug # debug.yml

on:
  workflow_dispatch:
    inputs:
      debug:
        description: Debug
        # type: boolean

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    # timeout-minutes: 60
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - run: exit 1

      - name: Set up tmate
        if: inputs.debug
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
